require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.colorscheme")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.completions")
require("plugin_config.gitsigns")
require("plugin_config.barbar")
require("plugin_config.vgit")
require("plugin_config.undotree")
require("plugin_config.gitgutter")
require("plugin_config.notify")
require("plugin_config.wilder")
require("plugin_config.lsp_signature")
require("plugin_config.toggleterm")
require("plugin_config.vimtex")
require("plugin_config.zenmode")
require("plugin_config.formatter")
require("plugin_config.markdown")
require("plugin_config.mason")
require("plugin_config.lspkind")
require("plugin_config.autopairs")
require("plugin_config.colorizer")
--require("plugin_config.hlslens")

--     [Themes]
require("plugin_config.gruvbox")
