require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.gruvbox")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.lsp_config")
require("plugin_config.completions")
require("plugin_config.gitsigns")
require("plugin_config.barbar")
require("plugin_config.vgit")
require("plugin_config.undotree")
require("plugin_config.ale")
require("plugin_config.gitgutter")
require("plugin_config.wilder")
require("plugin_config.fidget")
--require("plugin_config.VimTex")


