require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.gruvbox")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.lsp_config")
